version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./app:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#        restart: always
        depends_on:
            - php-fpm
            - pg-db

    php-fpm:
        build:
            context: docker/php-8.0-fpm-alpine
        volumes:
            - "./app:/var/www/html"
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal"
            PHP_IDE_CONFIG: serverName=${NGINX_HOST}

    pg-db:
        image: postgres:${POSTGRES_VERSION}
#        restart: always
        env_file:
            - ".env"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"

volumes:
    pgdata:
        external: true

#    mysqldb:
#        platform: linux/amd64
#        image: mysql:${MYSQL_VERSION}
#        container_name: ${MYSQL_HOST}
#        restart: always
#        env_file:
#            - ".env"
#        environment:
#            - MYSQL_DATABASE=${MYSQL_DATABASE}
#            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#            - MYSQL_USER=${MYSQL_USER}
#            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#        ports:
#            - "8989:3306"
#        volumes:
#            - "./data/db/mysql:/var/lib/mysql"

#    myadmin:
#        image: phpmyadmin/phpmyadmin:fpm-alpine
#        container_name: phpmyadmin-sber
#        ports:
#            - "8080:80"
#        environment:
#            - PMA_ARBITRARY=1
#            - PMA_HOST=${MYSQL_HOST}
#        restart: always
#        depends_on:
#            - mysqldb